apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer-postgersql
spec:
  selector:
    db: db-postgresql
  type: ClusterIP
  ports:
  - name: postgresqltcp
    port: 5432
    targetPort: 5432