apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: huseyin11/configserver:v01
          ports:
            - containerPort: 8888  # İmajın kullandığı port
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
          - name: GITHUB_KEY
            value: senin_github_classic_tokenin