server:
  port: 8181

spring:
  data:
    mongodb:
      uri: mongodb://root:toor@34.155.19.14:27017/UserProfileDB?authSource=admin
  cloud:
    config:
      uri: http://configserver-service:8888
  config:
    import: "configserver:"
  application:
    name: user-application