server:
  port: 8181

spring:
  data:
    mongodb:
      host: mongodb://root:toor@mongodb-service:27017/admin
      port: 27017
      username: root
      password: toor
      database: UserProfileDB